### ISSUE TITLE
Can't link Steam account

### ISSUE THREAD

**Issue by Riwyn** [HatScrubs/GameAccess#1]
When I try to connect my Steam account it gives me this error message:

undefined property: stdClass::$country

It comes after the page "Sign into scrubscribers.com using your Steam account" and clicking Sign in. As it returns to the scrubscribers site, it shows that message.

**Comment by stygiansabyss** [comment]
On it

**Comment by stygiansabyss** [comment]
Pushed an update.  Could you give this a shit now?

**Comment by Riwyn** [comment]
It made it worse. Now going to "Link Accounts" it just opens some sort of php page that definitely shouldn't be there. Also the link to this github page doesn't work from there now.

**Comment by stygiansabyss** [comment]
Good call, didn't catch that it failed.  Fixed the link page error and the footer link.

**Comment by Riwyn** [comment]
Now the first error says $state instead of $country :D

**Comment by stygiansabyss** [comment]
Ok, I have made them truly optional now.  If any of the three aren't there it will just ignore them.  Give it a final go for me.

**Comment by stygiansabyss** [comment]
I see in the database that it worked.  For some reason, your steam only shows up with a Country and not state/province or city.  That was a circumstance I didn't know could happen.

**Comment by Riwyn** [comment]
It worked! Thank you :D I really appreciate the work you've put on this website.

**Comment by stygiansabyss** [comment]
Thanks :)  Glad you are fixed up.
