### ISSUE TITLE
Permission to reference Hat films in creative writing

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#17]
Submitter: Ashley Connor (Konna117)
Email: ashkonna@live.co.uk
Hey guys,

I just wanted to know if you were okay with me referencing Trott, Ross, Smiffy and Hatfilms in general in a few of stories I'm writing?

One of them is a short story I submitted to University as a creative writing assignment. It was reviewed so well that the topic of publishing it came up and I recently had a meeting at Uni to discuss the idea and we're giving it the go ahead. It'll be turned into a one volume manga and that's it. I just need to finish the artwork and it'll be published in England and Japan.

The others are larger stories, one of them is a 10+ volume Light Novel that'll be primarily distributed in Japan, but it'll be written in English too. I just want to add random things in the stories as a reference to you all, such as seeing random visual 'Easter eggs' (i,e, seeing a background character wearing a Hatfilms logo t-shirt or something) so it isn't anything major. 

Just something I feel like doing.

Thanks :)

**Comment by stygiansabyss** [comment]
I have pointed Trott to this.  Will see how he wants to handle it.

**Comment by Akhawais** [comment]
Emailed
