### ISSUE TITLE
Linked accounts not linking to scrubscribers.com correctly

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#35]
Submitter: L Surendran
Email: surendranl@hotmail.co.uk
Neither my R\* Social club, nor my steam account are correctly linked to the account, as a result I have not been able to join the steam group nor the Crew

**Comment by Akhawais** [comment]
Waiting on reply

**Comment by Akhawais** [comment]
Added to R*, waiting for Steam group

**Comment by Akhawais** [comment]
Completed
