### ISSUE TITLE
Been waiting for a Invite to the Scrubcribers Crew (GTAV) since the 24th of march!

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#37]
Submitter: Pierre Åberg
Email: pirrellini@hotmail.com
Been waiting for a Invite to the Scrubcribers Crew (GTAV) since the 24th of march! I have my steam account, twitch account and Rockstar social club account linked on the scrubscriber website. It says that I need to link my Steam account with my RockStarSocialClub account but how do I do that  when I bought GTAV on the Rockstar website?  I have my Privacy settings on Rockstar Socialclub set to everyone! Help would be lovely! ;)

Scubscribers id: pirrelli2997
Twitch id: pirrelli2997
Rockstar Socialclub id: Pirrelli2997 https://socialclub.rockstargames.com/member/pirrelli2997
Steam id: Pirrelli

**Comment by Akhawais** [comment]
Emailed
