### ISSUE TITLE
How do I enter the scrubscribers GTA crew?

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#39]
Submitter: Connor
Email: Connortungate@live.co.uk
Hay, I've sub to Hatfilm's twitch channel and was just wondering how it is that I going the GTA crew, I have already link my accounts via Scrubscribers.com but I don't know if there is anything else required.

**Comment by Akhawais** [comment]
Waiting on reply

**Comment by Akhawais** [comment]
Added and done
