### ISSUE TITLE
Issue linking Social Club Account.

### ISSUE THREAD

**Issue by shla316** [HatScrubs/GameAccess#4]
Getting the error "Could not authenticate your Rockstar account".

**Comment by stygiansabyss** [comment]
What is your rockstar username?

**Comment by shla316** [comment]
shla316

**Comment by stygiansabyss** [comment]
Thank you for that.  You found an error in what I was expecting.  It is corrected now.  :)

**Comment by shla316** [comment]
OK, it works great now!  Thank you!

**Comment by stygiansabyss** [comment]
You are very welcome:)
