### ISSUE TITLE
Giving my best friend hare best birthday pressant ever. (with your help)

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#40]
Submitter: Bram Brouwer (aka sirBrouwer)
Email: b.brouwer.zakelijk@gmail.com
Dear Hat lads,

Fist of all I would like to thank you lads for your work and the wonderful extra gift in that thanks you I have been abel to meet some very dear friends of me.
One of my closest and dearest friend is Emily B. Everhart (aka Emmy Nyan the person who gave you all a scarf).
I know that she is as much if not even more of a fan of you lads and I would love to give here a very special (birthday) present.

That present I would like to give here will be one of your merch  bags (the one with just the HAT logo) that is sight by you three great lads.

The way I had thought that might work is as followed.
1. I buy the bag right mine own message on it first.
2. send the bag to you great lads via your PO box. 
3. You sign the bag your self (maybe even in a unboxing video)
4. You resent it to Emily here adres will be included in the package. And I will donate you guys the expanses before hand so to compensate you guys.

If you would be so kind as to help me out with this I would be so thanks full to you guys and I know that Emily would love it as much if not more.

Please let me know if this is even possible.
Much love Bram

**Comment by Akhawais** [comment]
Emailed

**Comment by Akhawais** [comment]
Reply received - guy is happy and will be sending the bag when he orders it
