### ISSUE TITLE
GTA Playlist

### ISSUE THREAD

**Issue by stygiansabyss** [HatScrubs/GameAccess#44]
Submitter: Vobbert
Email: vobbert@outlook.com
Hello,

https://socialclub.rockstargames.com/games/gtav/pc/playlists/playlist/U0eDletGKECAgjgOSaowPw

(Playlist: Race Variety by Vobbert)

Here is a playlist of races made by me. Off-road, in the city, high up in the sky, super cars, motorcycles, ramps, parkour. It has it all! I thought you might like to play it in one of your youtube GTA playlist videos. It is mostly 3 players max, so perfect for the three of you.

Kind regards,

Vobbert

**Comment by Akhawais** [comment]
Replied in email
