### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by JBird608** [HatScrubs/GameAccess#6]
Hey, Guys. 

Awesome work with the website so far, the work your doing is great. I have been working on a new design for the website to make it a little more finished. So if you get a chance please take a look and let me know what you think. I hope you like it, and if you would I would love to work on the project with you. 

Thanks, 
Joe.

![hat films scrub scribers](https://cloud.githubusercontent.com/assets/1952494/10515276/932e211e-734a-11e5-9e86-331fb82c1adb.png)

PS. This design has already been coded in HTML and CSS.

**Comment by stygiansabyss** [comment]
It is no shock that I am not the best designer and I do rather like your mock up.  We have a designer working on an actual non bootstrap theme already.  That being said, I'll still bring this to Trott's attention and see what we think.  What is it built on?  Also look at dev,scrubscribers.com for my upcoming change to the home page.

**Comment by JBird608** [comment]
This is built on Foundation, however most of the CSS is Custom. I only used Foundation for the Grid and a couple other elements. Thanks for the quick response.

**Comment by stygiansabyss** [comment]
Well at least we both use sass.  I have quite a few custom bits in mine as well.  I PMed trott on it, will keep you updated on the outcome sir :)

**Comment by JBird608** [comment]
Sounds great, is the PHP Custom Build or are you using a Framework, I also happen to be a Web Developer using PHP?

**Comment by stygiansabyss** [comment]
Its built on laravel with a lot of found packages and custom integrations.

**Comment by JBird608** [comment]
Ah, Awesome. Ironically thats the Framework I used. I was going to build in to Laravel but decided to straight up code it as I was not 100% on what you where using. As you haven't posted all the Laravel project files.

**Comment by stygiansabyss** [comment]
Not ironic per se.  If you dig PHP, laravel has likely at least caught your attention at some point.

In your mock up, once someone signs in, where are the menu items going to show?  Polls, admin section, profile updating, account linking, etc.

**Comment by JBird608** [comment]
As I see it, there are two options. 

1) They get added to the main menu bar, where support and login are currently. 
2) There is a difference pages once users have logged in, that has a different user interface.

Depends on Preference, _I can make the design work both ways_. 

Quick Question: Have you build a form the the HatFilms Guys to use when updating the sessions and are they stored in a database? 

Also does the website automatically generate Tweets for the HatFilms account using a package such as thujohn/twitter.

**Comment by stygiansabyss** [comment]
Yeah.  Anyone with the proper permissions has a few admin areas.  Live ones are sessions, servers and polls.  Dev version also has games and offline abilities as well.  All areas tested and modified if need be for mobile and working pretty well at the moment.  Added a nice typeahead input for games using algolia search even to make finding games easier.

**Comment by JBird608** [comment]
Awesome, well sounds good. I look forward to hearing from you and to see how the site develops. Drop me a tweet if you hear anything more or have any questions.

**Comment by stygiansabyss** [comment]
Will do sir.  Doubt I'll hear anything from trott till after the stream

**Comment by stygiansabyss** [comment]
Trott responded faster than expected.  Said he liked parts of it and thanked you for taking the time to do this, but he aims to stick with the design he's already been working on.  Sorry mate :(

**Comment by JBird608** [comment]
Ah, no worries. Keep up the good work. :D

**Comment by stygiansabyss** [comment]
Will do.  Thanks again sir :)
