### ISSUE TITLE
Text overflow / visibility issue on current website

### ISSUE THREAD

**Issue by wrincewind** [HatScrubs/GameAccess#7]
On the ['help' page](http://scrubscribers.com/help/user), on my current monitor, I'm unable to see the final line of text, right at the bottom - It runs underneath the footer.

![image](https://cloud.githubusercontent.com/assets/1457878/10544095/6024372a-7419-11e5-8cea-0fc7f326e02a.png)

Attached screenshot should show you what I mean - note the last sentence.

**Comment by stygiansabyss** [comment]
http://dev.scrubscribers.com/help/user  can you try on this version and tell me if you get the same results?  If so, what is your screen resolution?  I will mimic it and make sure it works out better.

**Comment by wrincewind** [comment]
Nope, that seems to fix the problem - tried it on a couple of screens and a couple of resolutions. 
for reference, my resolution was 1366x768, giving me a screen area [excluding bookmark bar, startbar, etc] of 1366x653.  

```
 On Friday, 16 October 2015, 16:57, Travis Blasingame <notifications@github.com> wrote:
```

 http://dev.scrubscribers.com/help/user can you try on this version and tell me if you get the same results? If so, what is your screen resolution? I will mimic it and make sure it works out better.—

**Comment by stygiansabyss** [comment]
Ok, that version should be going out today or tomorrow.  So you should be fixed up shortly.
